steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URL}:${SHORT_SHA}
      - -t
      - ${_IMAGE_URL}:staging
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - -f
      - frontend/Dockerfile
      - frontend/

images:
  - ${_IMAGE_URL}:${SHORT_SHA}
  - ${_IMAGE_URL}:staging

options:
  logging: CLOUD_LOGGING_ONLY
