# Generated by Django 5.2.10 on 2026-01-09 03:13

import django.core.validators
from django.db import migrations, models

import core.api.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_emailverifyrecord_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="image/default.png",
                max_length=200,
                upload_to="image/%Y/%m",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    ),
                    core.api.validators.ImageSizeValidator(),
                    core.api.validators.ImageMimeTypeValidator(),
                ],
                verbose_name="이미지",
            ),
        ),
    ]
