apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/component: add-on
    app.kubernetes.io/name: cluster-secret-store
  name: cluster-secret-store
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 5
  source:
    repoURL: git@github.com:DvwN-Lee/exam-platform.git
    path: argocd/infra/cluster-secret-store
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
