# Generated by Django 5.2.10 on 2026-01-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_indexes_and_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.subjectinfo', verbose_name='소속 과목'),
        ),
    ]
