# Generated by Django 5.2.9 on 2025-12-18 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0003_auto_20220527_1659'),
        ('testquestion', '0004_alter_optioninfo_create_time_alter_optioninfo_id_and_more'),
        ('user', '0003_alter_emailverifyrecord_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpapertestq',
            options={'ordering': ['order'], 'verbose_name': '시험지 문제 정보', 'verbose_name_plural': '시험지 문제 정보'},
        ),
        migrations.AddField(
            model_name='testpaperinfo',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='총 문항 수'),
        ),
        migrations.AddField(
            model_name='testpapertestq',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='문제 순서'),
        ),
        migrations.AddField(
            model_name='testpapertestq',
            name='score',
            field=models.IntegerField(default=5, verbose_name='문제 배점'),
        ),
        migrations.AddField(
            model_name='testscores',
            name='detail_records',
            field=models.JSONField(blank=True, default=dict, verbose_name='상세 답안 기록'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.subjectinfo', verbose_name='시험지 과목'),
        ),
        migrations.AlterField(
            model_name='testpapertestq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='test_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testpaper.testpaperinfo', verbose_name='시험지 정보'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentsinfo', verbose_name='학생 정보'),
        ),
        migrations.AlterUniqueTogether(
            name='testpapertestq',
            unique_together={('test_paper', 'test_question')},
        ),
        migrations.AddIndex(
            model_name='testpapertestq',
            index=models.Index(fields=['test_paper', 'order'], name='testpaper_t_test_pa_1f1ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='testscores',
            index=models.Index(fields=['user', 'test_paper'], name='testpaper_t_user_id_2010e0_idx'),
        ),
    ]
