# Generated by Django 5.2.9 on 2025-12-19 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_alter_examinationinfo_create_time_and_more'),
        ('testpaper', '0004_alter_testpapertestq_options_and_more'),
        ('user', '0003_alter_emailverifyrecord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscores',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.examinationinfo', verbose_name='시험 정보'),
        ),
        migrations.AddField(
            model_name='testscores',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='제출 여부'),
        ),
        migrations.AddField(
            model_name='testscores',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시험 시작 시간'),
        ),
        migrations.AddField(
            model_name='testscores',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제출 시간'),
        ),
        migrations.AddField(
            model_name='testscores',
            name='time_used',
            field=models.IntegerField(default=0, verbose_name='소요 시간(분)'),
        ),
        migrations.AddIndex(
            model_name='testscores',
            index=models.Index(fields=['exam', 'user'], name='testpaper_t_exam_id_411bf2_idx'),
        ),
    ]
