apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exam-platform.frontend.fullname" . }}
  namespace: {{ include "exam-platform.namespace" . }}
  labels:
    {{- include "exam-platform.frontend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "exam-platform.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exam-platform.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "exam-platform.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "exam-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "exam-platform.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
