# Generated by Django 5.2.9 on 2025-12-18 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testquestion', '0003_auto_20220527_1659'),
        ('user', '0003_alter_emailverifyrecord_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='optioninfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='creat_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='출제자'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='test_question/%Y/%m', verbose_name='시험 문제 사진'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='점수'),
        ),
        migrations.AlterField(
            model_name='testquestioninfo',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.subjectinfo', verbose_name='소속 과목'),
        ),
        migrations.AddIndex(
            model_name='testquestioninfo',
            index=models.Index(fields=['subject', 'tq_type', 'tq_degree'], name='testquestio_subject_4fbcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestioninfo',
            index=models.Index(fields=['is_del', 'is_share'], name='testquestio_is_del_442017_idx'),
        ),
    ]
