# Generated by Django 5.2.9 on 2025-12-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testquestion', '0004_alter_optioninfo_create_time_alter_optioninfo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestioninfo',
            old_name='creat_user',
            new_name='create_user',
        ),
    ]
